spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/travelzip/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379


  mail:
    username:
    password:
    host: smtp.naver.com
    port: '465'

