name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - develop
      - feature/#42
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      AWS_RDS_URL: ${{ secrets.AWS_RDS_URL }}
      AWS_MASTER_USER_NAME: ${{ secrets.AWS_MASTER_USER_NAME }}
      AWS_MASTER_USER_PASSWORD: ${{ secrets.AWS_MASTER_USER_PASSWORD }}
      NAVER_ID: ${{ secrets.NAVER_ID }}
      NAVER_PASSWORD: ${{ secrets.NAVER_PASSWORD }}
      ACCESS_TOKEN_SECRET_KEY: ${{ secrets.ACCESS_TOKEN_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make zip file
        run: zip -r ./travel.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./travel.zip s3://${{ secrets.AWS_S3_BUCKET }}/travel.zip

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name travel-zip-deploy \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name travel-zip-deploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=travel.zip \
          --region ${{ secrets.AWS_REGION }}